Ocr backend
ardium-pl/Ergis-new-repo pull request #1
Opened 2024-11-04 08:13 UTC by Grzesiek1212

2024-11-04 08:31 UTC, lolocob7 requested changes

2024-11-04 08:31 UTC, lolocob7 commented on server/src/index.ts
Żeby index.ts był jak najbardziej czytelny i prosty, zróbmy tutaj podział i dodajmy jeden plik, który będzie handlingował tzw. router. Przykład: 
![image](https://github.com/user-attachments/assets/34896ac2-46ae-4335-8862-c91a12dae77f)
Stwórz nowy plik w innym folderze, który będzie tworzył i exportował router:
![image](https://github.com/user-attachments/assets/78aa1835-12e7-4243-81a0-e104f47eb07e)
Do tego całą funkcjonalność, która znajduje się obecnie również możesz przerzucić do innego pliku, tak żeby index.ts był jak najprostszy i inne pliki zawierały funkcjonalność(podobnie jest zrobione w starym repo). Moja propozycja:

- server
  - src
    - api
      - polymerscan.ts
      - router.ts

2024-11-04 08:31 UTC, lolocob7 commented on server/src/index.ts
> +    const { SendID, pagesNumbers } = req.body;
SendID zamień na SendId

2024-11-04 08:33 UTC, lolocob7 requested changes

2024-11-04 08:33 UTC, lolocob7 commented on server/src/utils/ocrReader.ts
> +  const inputPdfFolder = "./input-pdf";
Zmień też nazwe tej mojej funckji na pdfOcr

2024-11-14 13:59 UTC, closed without merging

2024-11-14 13:59 UTC, Grzesiek1212 commented
zrobione